# -*- coding: utf-8 -*-
"""Aula1_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJw2KGp2t1gUreCAW__X3k3rxmCFRH3U
"""

#Importanto a biblioteca panda
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv", error_bad_lines=False, sep=";")

#Visualizando as 5 primeiras linhas
df.head()

df = df.rename(columns={"country":"Pais", "continent":"Continente","year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gpdPerCap":"PIB"})

df.head()

df.columns

df.dtypes

df.tail()

df.describe()

df["Continente"].unique()

Oceania = df.loc[df["Continente"] == "Oceania"]
Oceania.head()

Oceania["Continente"].unique()

df.groupby("Continente")["Pais"].nunique()

df.groupby("Ano")["Expectativa de vida"].mean()

